### ISSUE TITLE
No Overlays on CSGO

### ISSUE THREAD

**Issue by jljr222** [Mapeadores/ZombieReloaded#3]
This seems to be generally working on CSGO, but I've noticed that the overlays do not work on CSGO. Have you been able to rectify this?

**Comment by JMorell** [comment]
Round end overlay?

**Comment by jljr222** [comment]
Yup, the round end overlays.

**Comment by JMorell** [comment]
Added new CS:GO folder, with new files. https://github.com/JMorell/sm-zombiereloaded-3/commit/39be1476d5d3788fc6509369fc8dfd103dae8c4b

**Comment by jljr222** [comment]
I'll give it a shot and see if those work. Thanks!

**Comment by jljr222** [comment]
Looks like that doesn't work either. I'm not sure if the SRC is missing a fix you implemented, but it doesn't seem to work with the overlay.

**Comment by JMorell** [comment]
You have to change these commands in zombiereloaded.cfg

```
// Overlay, relative to "materials" folder, to display when zombies win the round. [Dependency: zr_roundend_overlay]
// Default: "overlays/zr/zombies_win"
zr_roundend_overlays_zombie "overlays/zr/cruisecar/c1024_zombies"
// Overlay, relative to "materials" folder, to display when humans win the round. [Dependency: zr_roundend_overlay]
// Default: "overlays/zr/humans_win"
zr_roundend_overlays_human "overlays/zr/cruisecar/c1024_humans"
```

**Comment by jljr222** [comment]
Here is what I have:

```
// ----------------------------------------------------------------------------
// Round End (core)
// ----------------------------------------------------------------------------

// Show specified overlay to players depending on winner when the round ends.
// Default: "1"
zr_roundend_overlay "1"

// Overlay, relative to "materials" folder, to display when zombies win the round. [Dependency: zr_roundend_overlay]
// Default: "overlays/zr/zombies_win"
zr_roundend_overlays_zombie "overlays/zr/cruisecar/c1024_zombies"

// Overlay, relative to "materials" folder, to display when humans win the round. [Dependency: zr_roundend_overlay]
// Default: "overlays/zr/humans_win"
zr_roundend_overlays_human "overlays/zr/cruisecar/c1024_humans"

// Balances the team every time the round ends. Disable this if you use something else to balance teams.
// Default: "1"
zr_roundend_balance_teams "1"
```

**Comment by jljr222** [comment]
Feel free to add me on steam and I can show you my test server with your build :)

http://steamcommunity.com/id/b0r3d

**Comment by JMorell** [comment]
These overlays works. Do you have files in your game folder?

**Comment by jljr222** [comment]
Yup, you can see my folder setup.
![untitled-1](https://cloud.githubusercontent.com/assets/3527321/20032781/45aaaf44-a368-11e6-8a8b-7b476ecc3374.png)

**Comment by jljr222** [comment]
So yea, I cannot figure out why it won't load up. I have all the files but it just doesn't show up. Is there some sort of config or something I need to change in order to enable overlays?

**Comment by JMorell** [comment]
https://forums.alliedmods.net/showthread.php?p=2366368

**Comment by jljr222** [comment]
Well, that might just do it!

**Comment by JMorell** [comment]
Fixed?
